milvus:
  host: 127.0.0.1
  port: 19530
  collection_name: persian_wikipedia_6
  db_name: Search_Env

model:
  name: /mnt/disk2/ehsan.tavan/search_env/embedding_model/multilingual-e5-small
  dim: 384

data:
  path: /mnt/disk2/ehsan.tavan/search_env/data/persian_wikipedia_100.jsonl
  chunk_size: 256
  chunk_overlap: 32